### ISSUE TITLE
Fix error when additional options are passed to the operation

### ISSUE THREAD

**Issue by akash-akya** [akash-akya/vix#82]
See https://github.com/kipcole9/image/issues/25
```
** (KeyError) key :type not found in: nil. If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
    (vix 0.15.0) lib/vix/vips/operation_helper.ex:13: anonymous fn/2 in Vix.Vips.OperationHelper.input_to_nif_terms/2
    (elixir 1.14.0) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.14.0) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (vix 0.15.0) lib/vix/vips/operation_helper.ex:222: Vix.Vips.OperationHelper.operation_call/4
    (vix 0.15.0) lib/vix/vips/image.ex:383: Vix.Vips.Image.new_from_buffer/2
    #cell:najz5o2ut5qv6nhqzmfdq5vzwfbnqvyw:9: Tester.get_dimension/1
    #cell:najz5o2ut5qv6nhqzmfdq5vzwfbnqvyw:40: (file)
```

**Comment by akash-akya** [comment]
Fixed by #83
